INSERT INTO `governorates` (`id`,`country_id`, `name_ar`, `name_en`) VALUES
(1,  1, 'القاهرة', 'Cairo'),
(2,  1, 'الجيزة', 'Giza'),
(3,  1, 'الأسكندرية', 'Alexandria'),
(4,  1, 'الدقهلية', 'Dakahlia'),
(5,  1, 'البحر الأحمر', 'Red Sea'),
(6,  1, 'البحيرة', 'Beheira'),
(7,  1, 'الفيوم', 'Fayoum'),
(8,  1, 'الغربية', 'Gharbiya'),
(9,  1, 'الإسماعلية', 'Ismailia'),
(10, 1, 'المنوفية', 'Menofia'),
(11, 1, 'المنيا', 'Minya'),
(12, 1, 'القليوبية', 'Qaliubiya'),
(13, 1, 'الوادي الجديد', 'New Valley'),
(14, 1, 'السويس', 'Suez'),
(15, 1, 'اسوان', 'Aswan'),
(16, 1, 'اسيوط', 'Assiut'),
(17, 1, 'بني سويف', 'Beni Suef'),
(18, 1, 'بورسعيد', 'Port Said'),
(19, 1, 'دمياط', 'Damietta'),
(20, 1, 'الشرقية', 'Sharkia'),
(21, 1, 'جنوب سيناء', 'South Sinai'),
(22, 1, 'كفر الشيخ', 'Kafr Al sheikh'),
(23, 1, 'مطروح', 'Matrouh'),
(24, 1, 'الأقصر', 'Luxor'),
(25, 1, 'قنا', 'Qena'),
(26, 1, 'شمال سيناء', 'North Sinai'),
(27, 1, 'سوهاج', 'Sohag');
